# Generated by Django 5.1.1 on 2025-02-18 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_restaurant_capacity"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="nickname",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
