# Generated by Django 5.1.1 on 2025-03-12 15:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_comment_delete_dummymodel"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="rating",
            constraint=models.CheckConstraint(
                condition=models.Q(("rating__gte", 1), ("rating__lte", 5)),
                name="rating_value_valid",
                violation_error_message="Rating invalid: must fall between 1 and 5.",
            ),
        ),
    ]
