# Generated by Django 5.1.1 on 2025-03-12 15:22

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_alter_restaurant_name"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="restaurant",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                name="unique_name_constraint",
            ),
        ),
    ]
