# Generated by Django 5.1.1 on 2025-03-12 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_task"),
    ]

    operations = [
        migrations.CreateModel(
            name="InprogressTask",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.task",),
        ),
    ]
